services:
  pdf-tools-frontend:
    build:
      context: ./tools/pdf-tools
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    restart: unless-stopped

  pdf-tools-backend:
    build:
      context: ./backend/services/pdf-tools
      dockerfile: Dockerfile
    ports:
      - "4001:8000"
    restart: unless-stopped
